<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>TravelLog T&C</title>
  <meta name="author" content="TravelLog Mgmt." />
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <style media="screen">
    body {
      background-color: black;
      color: white;
    }
  </style>

  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="TravelLog" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:title" content="TravelLog Terms and Conditions" />
  <meta property="og:description" content="Manage your Github projects from the palm of your hand." />
</head>

<body id="terms-and-conditions">
  <?php
  require_once "functions.php";
  ?>
  <div class="container-fluid">
    <div class="row terms-and-conditions-section">
      <div class="col-xs-12 text-center">
        <!-- <h5 class="title">Terms and Conditions</h5> -->
      </div>

      <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
        <div class="content">
          <p>
            TravelLog Mgmt., SRL ("TravelLog Mgmt.") operates TravelLog (as defined below), your use of TravelLog is governed by these Terms of Service (“Terms”), and your use of TravelLog constitutes your acceptance of the Terms.
          </p>
          <p>
            "TravelLog" (the "Service") means TravelLog project management solution made available at <a href="https://github.com/sn2606/TravelLog">Repository</a> (the “Site”) and any other software, sites, and services offered by TravelLog Mgmt. in connection therewith but does not include any sites, services, products, or offerings governed by other terms of use, or, other agreements between you and TravelLog Mgmt.. "Customer Data" means any data you make available to TravelLog Mgmt. or TravelLog from your GitHub account for the purpose of using TravelLog. "Content" means all content generated by TravelLog Mgmt. on your behalf (including metric data) and does not include Customer Data.
          </p>
          <p>
            We will endeavor to provide you with notice about major changes to the Terms or TravelLog and other changes (via email to the address on your account), but we make no guarantees. Other changes could be, without limitation, changes to payment policies, security patches, added or removed functionality, and other enhancements or restrictions to TravelLog. Your use of TravelLog after the Terms have changed constitutes your acceptance of the Terms as changed. You may reject changes to the Terms by terminating your subscription in accordance with the "Cancellation and Termination" section of these Terms of Service. TravelLog Mgmt. shall not be liable to you or to any third party for any change to TravelLog.
          </p>
          <p>
            Please use TravelLog responsibly and in compliance with these Terms. If you don't, we reserve the right to terminate your subscription in accordance with the "Cancellation and Termination" section of these Terms of Service.
          </p>

          <h2 class="section-title">1. Use of TravelLog</h2>
          <p>
            To use TravelLog, you must (i) Sign Up (ii) authorize TravelLog Mgmt. to access your Customer Data to provide TravelLog, (iii) provide accurate account information any time you register to use TravelLog, (iv) provide accurate GitHub account information when you register to use TravelLog, and (v) be a human over the age of 13. Uses by automated methods are not permitted. You grant TravelLog Mgmt. a non-exclusive, royalty-free, and worldwide license to use, store, and copy your Customer Data in order to provide TravelLog.
          </p>
          <p>
            You are responsible for the security of your passwords and for any use of your account. You may not allow multiple people to use the same account or otherwise access TravelLog in a manner intended to avoid incurring fees.
          </p>
          <p>
            You must comply with all applicable GitHub policies and terms of service. TravelLog Mgmt. is not responsible for any acts or omissions of GitHub whether related to your account or otherwise.
          </p>
          <p>
            TravelLog Mgmt. reserves the right to enforce quotas and usage limits (to any resources, including the API) at its sole discretion, with or without notice, which may result in TravelLog Mgmt. disabling or throttling your usage of the Service for any amount of time.
          </p>
          <p>
            You are responsible for obtaining access to TravelLog and that access may involve third party fees (such as Internet service provider or airtime charges). You are responsible for those fees. In addition, you must provide and are responsible for all equipment necessary to access the Site.
          </p>
          <p>
            You may not use TravelLog:
          </p>
          <ul>
            <li>
              for any illegal purpose, in any manner inconsistent with applicable laws, regulations, or ordinances, or to submit, post, upload, or otherwise transmit any Customer Data or Content that is unlawful, defamatory, libelous, invasive of another's privacy, abusive, threatening, harassing, vulgar, obscene, indecent or otherwise objectionable;
            </li>
            <li>
              to submit, post, upload or otherwise transmit any Customer Data or Content that infringes or otherwise violates the rights of any third party, including without limitation privacy rights, fiduciary rights and proprietary rights;
            </li>
            <li>
              to submit, post, upload or otherwise transmit Customer Data or Content that contains viruses, corrupted files, or any other similar software or programs that may damage the operation of TravelLog or another person's computer; or
            </li>
            <li>
              if you are a person barred from receiving TravelLog under the laws of the United States or other countries, including the country in which you are resident or from which you use TravelLog.
            </li>
          </ul>

          <h2 class="section-title">2. Cancellation and Termination</h2>
          <p>
            To cancel your subscription, account, and access to TravelLog, send us an email at <a href="mailto:hi@tryTravelLog.com?Subject=Cancel+Subscription">hi@tryTravelLog.com</a> instructing us to do so or cancel via the functionality on the Waffle website. If you paid for your subscription, TravelLog Mgmt. is not obligated to provide any refunds if you cancel your subscription or if TravelLog Mgmt. terminates your subscription because you breached these Terms. If your subscription is cancelled or terminated in accordance with the foregoing before the end of the current paid-up month, your cancellation will take effect immediately and you will not be charged again. All of your Customer Data and Content will, within a reasonable amount of time to be determined solely by TravelLog Mgmt., be deleted from TravelLog upon cancellation.
          </p>
          <p>
            You agree that TravelLog Mgmt., in its sole discretion and for any or no reason, may terminate or suspend your account. You agree that any termination of your access to the Service may be without prior notice, and you agree that TravelLog Mgmt. will not be liable to you or any third party for such termination. If you paid for your subscription, and TravelLog Mgmt. did not terminate or suspend your account due to your breach of these Terms, TravelLog Mgmt. will provide a pro-rata refund of unused subscription fees if it terminates or suspends your account in accordance with this paragraph.
          </p>

          <h2 class="section-title">3. Customer Data</h2>
          <p>
            TravelLog Mgmt. claims no ownership or control over any Customer Data. Except for the license expressly granted by you to TravelLog Mgmt. to provide TravelLog, you retain all right, title, and interest in and to Customer Data and you are responsible for protecting those rights and interests, as appropriate. Notwithstanding the foregoing, you grant to TravelLog Mgmt. for its use a worldwide, non-exclusive, royalty-free license to aggregate or compile Customer Data with customer data of other users of TravelLog so long as such aggregation or compilation omits any data that would enable the identification of you (“Aggregated Data”). TravelLog Mgmt. shall have a worldwide, perpetual, royalty-free license to use, modify, distribute and create derivative works based on such Aggregated Data, and as between you and TravelLog Mgmt., TravelLog Mgmt. shall own all compilations of the Aggregated Data, including all reports, statistics or analyses created or derived therefrom.
          </p>
          <p>
            You understand that projects in TravelLog will display Customer Data to you and any collaborators that you designate for that project. You are solely responsible for any collaborators and third-parties (including third-party services) that you allow to view Customer Data and entrust them at your own risk.
          </p>
          <p>
            You are solely responsible for configuring TravelLog to allow appropriate access to your Customer Data. TravelLog Mgmt. is not responsible if you fail to configure, or misconfigure, your project and inadvertently allow unauthorized parties to view any Customer Data.
          </p>

          <h2 class="section-title">4. Ideas and Feedback</h2>
          <p>
            As part of your use of TravelLog, you may choose, or we may invite you, to submit comments, feedback or ideas about TravelLog, including but not limited to ideas about improving TravelLog or our other offerings ("Ideas"). You hereby grant TravelLog Mgmt. a perpetual, royalty-free, unlimited, worldwide license to use and/or incorporate such Ideas into any TravelLog Mgmt. offering (including TravelLog) at any time in TravelLog Mgmt.’s sole discretion. Ideas you submit will not be afforded any confidential treatment by TravelLog Mgmt., regardless of whether you request such treatment or otherwise designate Ideas as proprietary or confidential.
          </p>

          <h2 class="section-title">5. External Sites and Content</h2>
          <p>
            The TravelLog may contain links to other websites or content (“Third Party Sites”). TravelLog Mgmt. does not endorse, sanction or verify the accuracy or ownership of the information contained in/on any Third Party Site or any products or services advertised on Third Party Sites. If you decide to leave the Site and navigate to Third Party Sites, or install any software or download content from any such Third Party Sites, you do so at your own risk. Once you access a Third Party Site through a link on our Site, you may be subject to the terms and conditions of such Third Party Site. You should review the applicable policies, including privacy and data gathering practices, of any Third Party Site to which you navigate from the Site, or relating to any software you use or install from a Third Party Site, including any applicable license agreement. Concerns regarding a Third Party Site should be directed to the Third Party Site itself. TravelLog Mgmt. bears no responsibility for any action associated with any Third Party Site.
          </p>

          <h2 class="section-title">6. License and Restrictions</h2>
          <p>
            Subject to and conditioned upon your agreement to and compliance with these Terms, we will make TravelLog available to you on a subscription basis solely for your own use and not for resale or to provide services to any third party.
          </p>
          <p>
            Excluding Third Party Sites and their related content, all of the content available on or through TravelLog, including without limitation, text, photographs, graphics, logos, trade/service marks, and/or audiovisual content, but expressly excluding Customer Data, is owned and/or controlled by TravelLog Mgmt., its licensors or TravelLog users and is protected, as applicable, by copyright, trademark, trade dress, patent, and trade secret laws, other proprietary rights, and international treaties. You acknowledge that TravelLog and any underlying technology or software used in connection with TravelLog contain our proprietary information.
          </p>
          <p>
            You will not, nor will you attempt to (or allow anyone else to or attempt to):
          </p>
          <ul>
            <li>
              copy, modify, create a derivative work of, reverse engineer, decompile or otherwise attempt to extract the source code of TravelLog or any part thereof;
            </li>
            <li>
              attempt to disable or circumvent any security or verification mechanism used by TravelLog;
            </li>
            <li>
              use TravelLog in any manner, or otherwise engage in any activity, that could damage, disable, overburden or impair our servers or networks, or interfere with or disrupt TravelLog or any other users' use or enjoyment of TravelLog.
            </li>
            <li>
              attempt to gain unauthorized access to any of TravelLog, member accounts, or computer systems or networks, through hacking, password mining or any other means.
            </li>
            <li>
              remove any notices of copyright, trademark or other proprietary rights contained in/on or accessible through TravelLog or in any content or other material obtained via TravelLog;
            </li>
            <li>
              use any robot, spider, website search/retrieval application, or other automated device, process or means to access, retrieve or index any portion of TravelLog;
            </li>
            <li>
              reformat or frame any portion of the web pages that are part of TravelLog;
            </li>
            <li>
              use TravelLog for commercial purposes not permitted under these Terms;
            </li>
            <li>
              in connection with your use of TravelLog, make unauthorized use of others’ GitHub accounts or Customer Data;
            </li>
            <li>
              create user accounts by automated means or under false or fraudulent pretenses;
            </li>
            <li>
              provide or use tracking or monitoring functionality in connection with TravelLog, including, without limitation, to identify other users’ actions or activities;
            </li>
            <li>
              impersonate or attempt to impersonate any other person or entity, including without limitation TravelLog Mgmt. or any employee, contractor or associate of TravelLog Mgmt.; or
            </li>
            <li>
              collect or store personal data about other users in connection with the prohibited activities described in this paragraph.
            </li>
          </ul>

          <h2 class="section-title">7. Open Source Software</h2>
          <p>
            Open source software licenses for components of TravelLog released under an open source license constitute separate written agreements. To the limited extent that the open source software licenses expressly supersede these Terms, the open source licenses govern your agreement with TravelLog Mgmt. only for the use of the components of TravelLog released under an open source license.
          </p>

          <h2 class="section-title">8. Monitoring of Content</h2>
          <p>
            You understand that TravelLog Mgmt. may access and disclose Customer Data or otherwise provide third parties access to it for the following reasons:
          </p>
          <ul>
            <li>
              to send an email message to you upon your request;
            </li>
            <li>
              to maintain the Site and TravelLog and to develop new and useful features and services;
            </li>
            <li>
              to follow a court order, subpoena, complaint or a lawful request from governmental authorities;
            </li>
            <li>
              to enforce these Terms;
            </li>
            <li>
              to respond to claims that any Customer Data or Content violates third party rights;
            </li>
            <li>
              to respond to your requests for customer service; and
            </li>
            <li>
              to protect the rights, property, or personal safety of TravelLog Mgmt., users of TravelLog Mgmt.’s offerings, including without limitation TravelLog, and the public.
            </li>
          </ul>

          <h2 class="section-title">9. Our Copyright Dispute Policy</h2>
          <p>
            TravelLog Mgmt. respects the intellectual property of others and requires that our users do the same. If you believe that material or content residing on or accessible through TravelLog infringes a copyright, please send a notice of copyright infringement containing the following information to the Designated Copyright Agent listed below:
          </p>
          <ul>
            <li>
              identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works;
            </li>
            <li>
              identification of the claimed infringing material and information reasonably sufficient to permit us to locate the material on TravelLog (providing the URL(s) of the claimed infringing material satisfies this requirement);
            </li>
            <li>
              information reasonably sufficient to permit us to contact you, such as an address, telephone number, and an email address;
            </li>
            <li>
              a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;
            </li>
            <li>
              a statement by you, made under penalty of perjury, that the above information in your notification is accurate and that you are the copyright owner or are authorized to act on the copyright owner's behalf; and
            </li>
            <li>
              your physical or electronic signature.
            </li>
          </ul>
          <p>
            Our Designated Copyright Agent for notification of claimed infringement can be reached by email at: hi@tryTravelLog.com or at the following postal address:
          </p>
          <p>
            Attn: Legal/Urgent, TravelLog Mgmt./TravelLog, 1011 Cassinoni, Montevideo, Uruguay
          </p>
          <p>
            <b>Disclaimer of Warranties:</b>
          </p>
          <p>
            IF YOU ACCESS TravelLog, YOU DO SO AT YOUR OWN RISK. WE PROVIDE TravelLog “AS IS,” “WITH ALL FAULTS” AND “AS AVAILABLE.” WE MAKE NO EXPRESS OR IMPLIED WARRANTIES OR GUARANTEES ABOUT TravelLog. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE HEREBY DISCLAIM ALL SUCH WARRANTIES, INCLUDING ALL STATUTORY WARRANTIES, WITH RESPECT TO TravelLog, INCLUDING WITHOUT LIMITATION ANY WARRANTIES THAT TravelLog IS MERCHANTABLE, OF SATISFACTORY QUALITY, ACCURATE, FIT FOR A PARTICULAR PURPOSE OR NEED, OR NON-INFRINGING. WE DO NOT GUARANTEE THAT THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF TravelLog WILL BE EFFECTIVE, RELIABLE OR ACCURATE OR WILL MEET YOUR REQUIREMENTS. WE DO NOT GUARANTEE THAT YOU WILL BE ABLE TO ACCESS OR USE TravelLog (EITHER DIRECTLY OR THROUGH THIRD-PARTY NETWORKS) AT TIMES OR LOCATIONS OF YOUR CHOOSING. WE ARE NOT RESPONSIBLE FOR THE ACCURACY, RELIABILITY, TIMELINESS OR COMPLETENESS OF INFORMATION PROVIDED BY ANY OTHER USERS OF TravelLog OR ANY OTHER DATA OR INFORMATION PROVIDED OR RECEIVED THROUGH TravelLog. EXCEPT AS EXPRESSLY SET FORTH HEREIN, TravelLog Mgmt. MAKES NO WARRANTIES ABOUT THE INFORMATION SYSTEMS, SOFTWARE AND FUNCTIONS MADE ACCESSIBLE BY OR THROUGH TravelLog OR ANY SECURITY ASSOCIATED WITH THE TRANSMISSION OF SENSITIVE INFORMATION. TravelLog Mgmt. DOES NOT WARRANT THAT TravelLog WILL OPERATE ERROR-FREE, THAT ERRORS IN THE SERVICE WILL BE FIXED, THAT LOSS OF DATA WILL NOT OCCUR, OR THAT TravelLog IS FREE OF COMPUTER VIRUSES, CONTAMINANTS OR OTHER HARMFUL ITEMS. UNDER NO CIRCUMSTANCES WILL TravelLog Mgmt., ANY OF OUR AFFILIATES, DISTRIBUTORS, PARTNERS, LICENSORS, AND/OR ANY OF OUR OR THEIR DIRECTORS, OFFICERS, EMPLOYEES, CONSULTANTS, AGENTS, OR OTHER REPRESENTATIVES BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY YOUR RELIANCE ON INFORMATION OBTAINED THROUGH THE SERVICE.
          </p>

          <h2 class="section-title">10. Limitations on Liability</h2>
          <p>
            YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY DISPUTE WITH US IS THE CANCELLATION OF YOUR USE OF TravelLog. IN NO EVENT SHALL WE BE LIABLE TO YOU (OR TO ANY THIRD PARTY CLAIMING UNDER OR THROUGH YOU) FOR ANY DAMAGES WHATSOEVER, INCLUDING, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES OR ANY BODILY INJURY, EMOTIONAL DISTRESS, DEATH OR ANY OTHER DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE TravelLog, WHETHER ON-LINE OR OFF-LINE, OR OTHERWISE IN CONNECTION WITH TravelLog. THESE EXCLUSIONS APPLY TO ANY CLAIMS FOR LOST PROFITS, LOST DATA, LOSS OF GOODWILL OR BUSINESS REPUTATION, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, ANY OTHER COMMERCIAL DAMAGES OR LOSSES, OR ANY PERSONAL INJURY OR PROPERTY DAMAGES, EVEN IF WE KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. TravelLog Mgmt.’S LIABILITY UNDER THESE TERMS SHALL BE LIMITED TO THE FEES YOU PAID TravelLog Mgmt. IN THE TWELVE MONTHS PRIOR TO THE DATE THE CLAIM AROSE. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH STATES OR JURISDICTIONS, OUR LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.
          </p>

          <h2 class="section-title">11. Indemnification</h2>
          <p>
            You agree to hold harmless and indemnify TravelLog Mgmt., and its subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers or partners from and against any third party claim arising from or in any way related to (a) your breach of the Terms, (b) your use of TravelLog, (c) your violation of applicable laws, rules or regulations in connection with TravelLog, or (d) your Customer Data, including any liability or expense arising from all claims, losses, damages (actual and consequential), suits, judgments, litigation costs and attorneys' fees, of every kind and nature. In such a case, TravelLog Mgmt. will provide you with written notice of such claim, suit or action.
          </p>

          <h2 class="section-title">12. Choice of Law and Dispute Resolution</h2>
          <p>
            These Terms will be governed by and construed in accordance with the laws of the State of California without giving effect to principles of conflict of laws, and the parties consent to the jurisdiction of the federal courts of the State of California. Each party irrevocably submits to the jurisdiction and venue of any such court in any such action or proceeding. The United Nations Convention on Contracts for the International Sale of Goods will not apply to These Terms.
          </p>

          <h2 class="section-title">13. General Legal Terms</h2>
          <p>
            These Terms constitute the whole legal agreement between you and TravelLog Mgmt. and govern your use of the Service and completely replace any prior agreements between you and TravelLog Mgmt., written or oral, in relation to TravelLog.
          </p>
          <p>
            If any part of the Terms is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect.
          </p>
          <p>
            The failure of TravelLog Mgmt. to exercise or enforce any right or provision of the Terms shall not constitute a waiver of such right or provision.
          </p>
          <p>
            TravelLog Mgmt. shall not be liable for failing or delaying performance of its obligations resulting from any condition beyond its reasonable control, including but not limited to, governmental action, acts of terrorism, earthquake, fire, flood or other acts of God, labor conditions, power failures, and Internet disturbances.
          </p>
          <p>
            TravelLog Mgmt. may assign this contract at any time to any parent, subsidiary, or any affiliated company, or as part of the sale to, merger with, or other transfer of our company to another entity. You may not assign these Terms.
          </p>
          <p>
            These Terms are adapted from the Waffle.io Terms of Service, which is an adaption of the CodeClimate Terms of Service, which is an adaption of the Heroku Terms of Service, which in turn is an adaptation of the Google App Engine Terms of Service. The original work has been modified with permission under the Creative Commons Attribution 3.0 License. Neither CA, Inc, CodeClimate, LLC, Heroku, Inc. nor Google, Inc. is connected with, nor do they sponsor or endorse, TravelLog Mgmt. or its use of the work.
          </p>
          <p>
            Version 1.0, Feb 21, 2021
          </p>

        </div>
      </div>
    </div>
  </div>
</body>

</html>